[package]
name = "tujiao-vision"
version = "0.1.0"
description = "涂胶检测上位机"
edition = "2021"

[lib]
name = "tujiao_vision_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
